Cross Validation - evaluating the model performance in order to find the crrt model for the problem solving
for training the model there are 3 ways
training option - 1 - training the model with 100% data
training option - 2 - training the model by spliting the data into training and testing
training option - 3 - k-fold cross validation

K-fold cross-validation is a valuable tool in machine learning model evaluation and hyperparameter tuning, helping researchers and practitioners make more informed decisions about model performance and generalization.It is a resampling procedure that helps to provide a more accurate estimate of a model's performance compared to using a single train-test split.

<img src="https://editor.analyticsvidhya.com/uploads/37094K%20-fold%20cross%20vaslidation.png" style="width:400px;height:200px;">
<h1 color="blue">K-Fold cross validation</h1>

In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np 
import pandas as pd
from sklearn.datasets import load_digits

digits = load_digits()

In [2]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(digits.data,digits.target,test_size = 0.3)

In [3]:
lr = LogisticRegression()
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

C:\Users\Bezawada\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9611111111111111

In [4]:
model = SVC()
model.fit(x_train,y_train)
model.score(x_test,y_test)

0.9907407407407407

In [5]:
model3 = RandomForestClassifier()
model3.fit(x_train,y_train)
model3.score(x_test,y_test)

0.9722222222222222

In [6]:
#eg for k- flod cross validation
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [7]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)


[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [8]:
def get_score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [9]:
get_score(SVC(),x_train,x_test,y_train,y_test)

0.9907407407407407

In [10]:
from sklearn.model_selection import StratifiedKFold #similar to KFold but it divides uniformly
skf = StratifiedKFold(n_splits = 3)

In [11]:
scores_l = []
scores_svm = []
scores_rf = []

for train_index,test_index in kf.split(digits.data):
    x_train,x_test,y_train,y_test = digits.data[train_index],digits.data[test_index], digits.target[train_index],digits.target[test_index]
    scores_l.append(get_score(SVC(),x_train,x_test,y_train,y_test)) 
    scores_svm .append(get_score(LogisticRegression(),x_train,x_test,y_train,y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators = 4),x_train,x_test,y_train,y_test))

C:\Users\Bezawada\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Bezawada\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/lin

In [12]:
scores_l

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [13]:
scores_svm

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [14]:
scores_rf

[0.8230383973288815, 0.7996661101836394, 0.8213689482470785]

In [15]:
#instead of doing all this we can just use the functio cross validation
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(),digits.data,digits.target)

C:\Users\Bezawada\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Bezawada\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/lin

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [16]:
cross_val_score(RandomForestClassifier(n_estimators = 10),digits.data,digits.target)

array([0.92777778, 0.85833333, 0.94150418, 0.94428969, 0.88857939])

In [17]:
cross_val_score(RandomForestClassifier(n_estimators = 40),digits.data,digits.target)

array([0.93055556, 0.90555556, 0.95264624, 0.95543175, 0.91922006])